Update Picasso version to avoid conflicts with other libraries
push-platform/fcm-channel-android pull request #34
Opened 2020-02-04 03:24 UTC by ericksprengel

Public interface changed on https://github.com/square/picasso/commit/e7e919232fe2b15772a7fcd9e15ead2304c66fae
and it was conflicting with latest In-App-Messaging version.

https://github.com/firebase/firebase-android-sdk/blob/master/firebase-inappmessaging-display/firebase-inappmessaging-display.gradle#L82

Dependency tree resolution for Picasso:
```
+--- org.bitbucket.ilhasoft.support-core:media:0.9.0
|    \--- com.squareup.picasso:picasso:2.5.2 -> 2.71828 (*)
\--- com.squareup.picasso:picasso:2.5.2 -> 2.71828 (*)
```

2020-02-04 15:41 UTC, ericksprengel commented
unfortunately `org.bitbucket.ilhasoft.support-core:media:0.9.0` is using `2.5.2` version too.
```
com.squareup.picasso:picasso:2.5.2 -> 2.71828
```

full dependency tree:
```

+--- org.bitbucket.ilhasoft.support-core:media:0.9.0
|    +--- org.bitbucket.ilhasoft.support-core:core:0.9.0
|    |    +--- me.zhanghai.android.materialprogressbar:library:1.3.0
|    |    |    +--- androidx.appcompat:appcompat:1.0.0 -> 1.0.2 (*)
|    |    |    \--- androidx.annotation:annotation:1.0.0
|    |    \--- androidx.appcompat:appcompat:1.0.0 -> 1.0.2 (*)
|    +--- org.bitbucket.ilhasoft.support-core:widget:0.9.0
|    |    \--- com.google.android.material:material:1.0.0
|    |         +--- androidx.annotation:annotation:1.0.0
|    |         +--- androidx.core:core:1.0.0 -> 1.0.1 (*)
|    |         +--- androidx.legacy:legacy-support-core-ui:1.0.0 (*)
|    |         +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    |         +--- androidx.fragment:fragment:1.0.0 (*)
|    |         +--- androidx.transition:transition:1.0.0
|    |         |    +--- androidx.annotation:annotation:1.0.0
|    |         |    \--- androidx.core:core:1.0.0 -> 1.0.1 (*)
|    |         +--- androidx.appcompat:appcompat:1.0.0 -> 1.0.2 (*)
|    |         +--- androidx.cardview:cardview:1.0.0
|    |         |    \--- androidx.annotation:annotation:1.0.0
|    |         \--- androidx.recyclerview:recyclerview:1.0.0 (*)
|    +--- com.github.rubensousa:BottomSheetBuilder:1.5
|    +--- com.squareup.picasso:picasso:2.5.2 -> 2.71828
|    |    +--- com.squareup.okhttp3:okhttp:3.10.0 -> 3.12.2 (*)
|    |    +--- androidx.annotation:annotation:1.0.0
|    |    \--- androidx.exifinterface:exifinterface:1.0.0
|    |         \--- androidx.annotation:annotation:1.0.0
|    \--- com.google.android.material:material:1.0.0 (*)
```

2020-02-04 19:36 UTC, allancslima commented
Thanks for this PR!

I'll provide an update to `org.bitbucket.ilhasoft.support-core.media` soon.

2020-02-05 12:51 UTC, allancslima commented
Hey @ericksprengel, can you update the `org.bitbucket.ilhasoft.support-core:media` dependency to version `1.0.0`?

Jitpack: https://jitpack.io/#org.bitbucket.ilhasoft/support-core/

2020-02-20 13:55 UTC, koallann requested changes
Please update the `org.bitbucket.ilhasoft.support-core:media` dependency to version `1.0.0`.

2020-03-25 16:05 UTC, ericksprengel commented
@koallann , I updated org.bitbucket.ilhasoft.support-core:media to version 1.0.0.

I couldn't test this last commit  (24ae93d45eba964b2f90001d008202dd5c79856d) because the sdk was removed from my app for now.
I just tested the previous commit (be5561a3fcd5ccc8ffe6a9ee36af328b7ba61876)

2024-01-12 14:29 UTC, closed without merging